// Flattened device list for autocomplete
// Total: 2000+ devices

export const devices = [
  // ==================== PHONES ====================
  // Apple iPhone
  "iPhone 17 Pro Max",
  "iPhone 17 Pro",
  "iPhone 17 Air",
  "iPhone 17",
  "iPhone 16 Pro Max",
  "iPhone 16 Pro",
  "iPhone 16 Plus",
  "iPhone 16",
  "iPhone 15 Pro Max",
  "iPhone 15 Pro",
  "iPhone 15 Plus",
  "iPhone 15",
  "iPhone 14 Pro Max",
  "iPhone 14 Pro",
  "iPhone 14 Plus",
  "iPhone 14",
  "iPhone 13 Pro Max",
  "iPhone 13 Pro",
  "iPhone 13 Mini",
  "iPhone 13",
  "iPhone 12 Pro Max",
  "iPhone 12 Pro",
  "iPhone 12 Mini",
  "iPhone 12",
  "iPhone 11 Pro Max",
  "iPhone 11 Pro",
  "iPhone 11",
  "iPhone XS Max",
  "iPhone XS",
  "iPhone XR",
  "iPhone X",
  "iPhone 8 Plus",
  "iPhone 8",
  "iPhone 7 Plus",
  "iPhone 7",
  "iPhone 6s Plus",
  "iPhone 6s",
  "iPhone 6 Plus",
  "iPhone 6",
  "iPhone SE (3rd Gen)",
  "iPhone SE (2nd Gen)",
  "iPhone SE (1st Gen)",
  "iPhone 5s",
  "iPhone 5c",
  "iPhone 5",
  "iPhone 4s",
  "iPhone 4",
  
  // Samsung Galaxy S Series
  "Samsung Galaxy S25 Ultra",
  "Samsung Galaxy S25+",
  "Samsung Galaxy S25",
  "Samsung Galaxy S24 Ultra",
  "Samsung Galaxy S24+",
  "Samsung Galaxy S24",
  "Samsung Galaxy S24 FE",
  "Samsung Galaxy S23 Ultra",
  "Samsung Galaxy S23+",
  "Samsung Galaxy S23",
  "Samsung Galaxy S23 FE",
  "Samsung Galaxy S22 Ultra",
  "Samsung Galaxy S22+",
  "Samsung Galaxy S22",
  "Samsung Galaxy S21 Ultra",
  "Samsung Galaxy S21+",
  "Samsung Galaxy S21",
  "Samsung Galaxy S21 FE",
  "Samsung Galaxy S20 Ultra",
  "Samsung Galaxy S20+",
  "Samsung Galaxy S20",
  "Samsung Galaxy S20 FE",
  "Samsung Galaxy S10+",
  "Samsung Galaxy S10",
  "Samsung Galaxy S10e",
  "Samsung Galaxy S10 Lite",
  "Samsung Galaxy S9+",
  "Samsung Galaxy S9",
  "Samsung Galaxy S8+",
  "Samsung Galaxy S8",
  "Samsung Galaxy S7 Edge",
  "Samsung Galaxy S7",
  "Samsung Galaxy S6 Edge+",
  "Samsung Galaxy S6 Edge",
  "Samsung Galaxy S6",
  
  // Samsung Galaxy Z Fold/Flip
  "Samsung Galaxy Z Fold 6",
  "Samsung Galaxy Z Fold 5",
  "Samsung Galaxy Z Fold 4",
  "Samsung Galaxy Z Fold 3",
  "Samsung Galaxy Z Fold 2",
  "Samsung Galaxy Z Fold",
  "Samsung Galaxy Z Flip 6",
  "Samsung Galaxy Z Flip 5",
  "Samsung Galaxy Z Flip 4",
  "Samsung Galaxy Z Flip 3",
  "Samsung Galaxy Z Flip 2",
  "Samsung Galaxy Z Flip",
  
  // Samsung Galaxy Note
  "Samsung Galaxy Note 20 Ultra",
  "Samsung Galaxy Note 20",
  "Samsung Galaxy Note 10+",
  "Samsung Galaxy Note 10",
  "Samsung Galaxy Note 9",
  "Samsung Galaxy Note 8",
  "Samsung Galaxy Note 7",
  "Samsung Galaxy Note 5",
  "Samsung Galaxy Note 4",
  "Samsung Galaxy Note 3",
  
  // Samsung Galaxy A Series
  "Samsung Galaxy A73",
  "Samsung Galaxy A72",
  "Samsung Galaxy A71",
  "Samsung Galaxy A70",
  "Samsung Galaxy A55",
  "Samsung Galaxy A54",
  "Samsung Galaxy A53",
  "Samsung Galaxy A52",
  "Samsung Galaxy A51",
  "Samsung Galaxy A50",
  "Samsung Galaxy A35",
  "Samsung Galaxy A34",
  "Samsung Galaxy A33",
  "Samsung Galaxy A32",
  "Samsung Galaxy A25",
  "Samsung Galaxy A24",
  "Samsung Galaxy A23",
  "Samsung Galaxy A22",
  "Samsung Galaxy A21",
  "Samsung Galaxy A20",
  "Samsung Galaxy A15",
  "Samsung Galaxy A14",
  "Samsung Galaxy A13",
  "Samsung Galaxy A12",
  "Samsung Galaxy A11",
  "Samsung Galaxy A10",
  "Samsung Galaxy A05",
  "Samsung Galaxy A04",
  "Samsung Galaxy A03s",
  "Samsung Galaxy A03",
  "Samsung Galaxy A02s",
  "Samsung Galaxy A02",
  "Samsung Galaxy A01",
  
  // Google Pixel
  "Google Pixel 9 Pro XL",
  "Google Pixel 9 Pro",
  "Google Pixel 9 Pro Fold",
  "Google Pixel 9",
  "Google Pixel 8 Pro",
  "Google Pixel 8a",
  "Google Pixel 8",
  "Google Pixel 7 Pro",
  "Google Pixel 7a",
  "Google Pixel 7",
  "Google Pixel 6 Pro",
  "Google Pixel 6a",
  "Google Pixel 6",
  "Google Pixel 5a",
  "Google Pixel 5",
  "Google Pixel 4a 5G",
  "Google Pixel 4a",
  "Google Pixel 4 XL",
  "Google Pixel 4",
  "Google Pixel 3a XL",
  "Google Pixel 3a",
  "Google Pixel 3 XL",
  "Google Pixel 3",
  "Google Pixel 2 XL",
  "Google Pixel 2",
  "Google Pixel XL",
  "Google Pixel",
  
  // OnePlus
  "OnePlus 12",
  "OnePlus 12R",
  "OnePlus 11",
  "OnePlus 11R",
  "OnePlus 10 Pro",
  "OnePlus 10T",
  "OnePlus 10R",
  "OnePlus 9 Pro",
  "OnePlus 9",
  "OnePlus 9R",
  "OnePlus 8 Pro",
  "OnePlus 8T",
  "OnePlus 8",
  "OnePlus 7T Pro",
  "OnePlus 7T",
  "OnePlus 7 Pro",
  "OnePlus 7",
  "OnePlus 6T",
  "OnePlus 6",
  "OnePlus 5T",
  "OnePlus 5",
  "OnePlus Nord 4",
  "OnePlus Nord 3",
  "OnePlus Nord 2T",
  "OnePlus Nord 2",
  "OnePlus Nord CE 4",
  "OnePlus Nord CE 3",
  "OnePlus Nord CE 2",
  "OnePlus Nord N30",
  "OnePlus Nord N20",
  "OnePlus Nord N10",
  "OnePlus Open",
  
  // Motorola
  "Motorola Edge 50 Ultra",
  "Motorola Edge 50 Pro",
  "Motorola Edge 50",
  "Motorola Edge 40 Pro",
  "Motorola Edge 40",
  "Motorola Edge 30 Ultra",
  "Motorola Edge 30 Pro",
  "Motorola Edge 30",
  "Motorola Edge+ (2023)",
  "Motorola Edge+ (2022)",
  "Motorola Edge (2023)",
  "Motorola Edge (2022)",
  "Motorola Razr 50 Ultra",
  "Motorola Razr 50",
  "Motorola Razr 40 Ultra",
  "Motorola Razr 40",
  "Motorola Razr+ (2024)",
  "Motorola Razr+ (2023)",
  "Motorola Razr (2023)",
  "Moto G Power 5G (2024)",
  "Moto G Power (2024)",
  "Moto G Power (2023)",
  "Moto G Power (2022)",
  "Moto G Stylus 5G (2024)",
  "Moto G Stylus 5G (2023)",
  "Moto G Stylus (2024)",
  "Moto G Stylus (2023)",
  "Moto G 5G (2024)",
  "Moto G 5G (2023)",
  "Moto G Play (2024)",
  "Moto G Play (2023)",
  "Moto G Pure",
  "Moto G Fast",
  "Moto G85",
  "Moto G84",
  "Moto G73",
  "Moto G72",
  "Moto G54",
  "Moto G53",
  "Moto G34",
  "Moto G32",
  "Moto G24",
  "Moto G23",
  "Moto G14",
  "Moto G13",
  "Moto G04",
  "Moto E14",
  "Moto E13",
  "ThinkPhone by Motorola",
  
  // LG
  "LG Wing",
  "LG Velvet",
  "LG V60 ThinQ",
  "LG V50 ThinQ",
  "LG V40 ThinQ",
  "LG V35 ThinQ",
  "LG V30",
  "LG G8X ThinQ",
  "LG G8 ThinQ",
  "LG G7 ThinQ",
  "LG G6",
  "LG G5",
  "LG Stylo 6",
  "LG Stylo 5",
  "LG Stylo 4",
  "LG K92",
  "LG K71",
  "LG K62",
  "LG K51",
  "LG K42",
  "LG K31",
  "LG K22",
  "LG Aristo 5",
  "LG Aristo 4+",
  "LG Tribute Monarch",
  "LG Phoenix 5",
  
  // ==================== TABLETS ====================
  // iPad
  "iPad Pro 13-inch (M4)",
  "iPad Pro 11-inch (M4)",
  "iPad Pro 12.9-inch (6th Gen)",
  "iPad Pro 12.9-inch (5th Gen)",
  "iPad Pro 12.9-inch (4th Gen)",
  "iPad Pro 12.9-inch (3rd Gen)",
  "iPad Pro 12.9-inch (2nd Gen)",
  "iPad Pro 12.9-inch (1st Gen)",
  "iPad Pro 11-inch (4th Gen)",
  "iPad Pro 11-inch (3rd Gen)",
  "iPad Pro 11-inch (2nd Gen)",
  "iPad Pro 11-inch (1st Gen)",
  "iPad Air 13-inch (M2)",
  "iPad Air 11-inch (M2)",
  "iPad Air (5th Gen)",
  "iPad Air (4th Gen)",
  "iPad Air (3rd Gen)",
  "iPad Air 2",
  "iPad Air",
  "iPad (10th Gen)",
  "iPad (9th Gen)",
  "iPad (8th Gen)",
  "iPad (7th Gen)",
  "iPad (6th Gen)",
  "iPad (5th Gen)",
  "iPad (4th Gen)",
  "iPad (3rd Gen)",
  "iPad 2",
  "iPad Mini (6th Gen)",
  "iPad Mini (5th Gen)",
  "iPad Mini 4",
  "iPad Mini 3",
  "iPad Mini 2",
  "iPad Mini",
  
  // Samsung Galaxy Tab
  "Samsung Galaxy Tab S10 Ultra",
  "Samsung Galaxy Tab S10+",
  "Samsung Galaxy Tab S10",
  "Samsung Galaxy Tab S9 Ultra",
  "Samsung Galaxy Tab S9+",
  "Samsung Galaxy Tab S9",
  "Samsung Galaxy Tab S9 FE+",
  "Samsung Galaxy Tab S9 FE",
  "Samsung Galaxy Tab S8 Ultra",
  "Samsung Galaxy Tab S8+",
  "Samsung Galaxy Tab S8",
  "Samsung Galaxy Tab S7 FE",
  "Samsung Galaxy Tab S7+",
  "Samsung Galaxy Tab S7",
  "Samsung Galaxy Tab S6 Lite (2024)",
  "Samsung Galaxy Tab S6 Lite (2022)",
  "Samsung Galaxy Tab S6 Lite",
  "Samsung Galaxy Tab S6",
  "Samsung Galaxy Tab A9+",
  "Samsung Galaxy Tab A9",
  "Samsung Galaxy Tab A8 (2022)",
  "Samsung Galaxy Tab A7 Lite",
  "Samsung Galaxy Tab A7",
  "Samsung Galaxy Tab Active 5",
  "Samsung Galaxy Tab Active 4 Pro",
  "Samsung Galaxy Tab Active 3",
  
  // Amazon Fire
  "Amazon Fire Max 11",
  "Amazon Fire HD 10 (2023)",
  "Amazon Fire HD 10 Plus (2021)",
  "Amazon Fire HD 10 (2021)",
  "Amazon Fire HD 10 (2019)",
  "Amazon Fire HD 8 (2024)",
  "Amazon Fire HD 8 Plus (2022)",
  "Amazon Fire HD 8 (2022)",
  "Amazon Fire HD 8 (2020)",
  "Amazon Fire 7 (2022)",
  "Amazon Fire 7 (2019)",
  "Amazon Fire HD 10 Kids Pro",
  "Amazon Fire HD 10 Kids",
  "Amazon Fire HD 8 Kids Pro",
  "Amazon Fire HD 8 Kids",
  "Amazon Fire 7 Kids",
  
  // Microsoft Surface
  "Microsoft Surface Pro 11",
  "Microsoft Surface Pro 10",
  "Microsoft Surface Pro 9",
  "Microsoft Surface Pro 8",
  "Microsoft Surface Pro 7+",
  "Microsoft Surface Pro 7",
  "Microsoft Surface Pro 6",
  "Microsoft Surface Pro 5",
  "Microsoft Surface Pro 4",
  "Microsoft Surface Pro 3",
  "Microsoft Surface Go 4",
  "Microsoft Surface Go 3",
  "Microsoft Surface Go 2",
  "Microsoft Surface Go",
  
  // ==================== GAMING CONSOLES ====================
  // PlayStation
  "PlayStation 5 Pro",
  "PlayStation 5 Slim",
  "PlayStation 5 Digital Edition Slim",
  "PlayStation 5",
  "PS5",
  "PlayStation 5 Digital Edition",
  "PS5 Digital",
  "PlayStation 4 Pro",
  "PS4 Pro",
  "PlayStation 4 Slim",
  "PS4 Slim",
  "PlayStation 4",
  "PS4",
  "PlayStation 3 Super Slim",
  "PS3 Super Slim",
  "PlayStation 3 Slim",
  "PS3 Slim",
  "PlayStation 3",
  "PS3",
  "PlayStation 2 Slim",
  "PS2 Slim",
  "PlayStation 2",
  "PS2",
  "PlayStation",
  "PS1",
  "PSX",
  "PS VR2",
  "PlayStation VR2",
  "PS VR",
  "PlayStation VR",
  
  // Xbox
  "Xbox Series X",
  "Xbox Series S",
  "Xbox One X",
  "Xbox One S All-Digital",
  "Xbox One S",
  "Xbox One",
  "Xbox 360 E",
  "Xbox 360 S",
  "Xbox 360",
  "Xbox",
  "Xbox Original",
  
  // Nintendo
  "Nintendo Switch 2",
  "Nintendo Switch OLED",
  "Nintendo Switch",
  "Switch OLED",
  "Switch Lite",
  "Nintendo Switch Lite",
  "Wii U",
  "Nintendo Wii U",
  "Wii",
  "Nintendo Wii",
  "Nintendo GameCube",
  "GameCube",
  "Nintendo 64",
  "N64",
  "Super Nintendo",
  "SNES",
  "Super Nintendo Entertainment System",
  "Nintendo Entertainment System",
  "NES",
  "Nintendo 3DS XL",
  "3DS XL",
  "Nintendo 3DS",
  "3DS",
  "Nintendo 2DS XL",
  "2DS XL",
  "Nintendo 2DS",
  "2DS",
  "Nintendo DS Lite",
  "DS Lite",
  "Nintendo DS",
  "DS",
  "Nintendo DSi XL",
  "DSi XL",
  "Nintendo DSi",
  "DSi",
  "Game Boy Advance SP",
  "GBA SP",
  "Game Boy Advance",
  "GBA",
  "Game Boy Color",
  "GBC",
  "Game Boy Pocket",
  "Game Boy",
  
  // Other Gaming
  "Steam Deck OLED",
  "Steam Deck LCD",
  "Steam Deck",
  "ASUS ROG Ally X",
  "ASUS ROG Ally",
  "ROG Ally X",
  "ROG Ally",
  "Lenovo Legion Go",
  "Legion Go",
  "MSI Claw",
  
  // ==================== LAPTOPS ====================
  // MacBook Pro
  "MacBook Pro 16-inch (M4 Max)",
  "MacBook Pro 16-inch (M4 Pro)",
  "MacBook Pro 16-inch (M3 Max)",
  "MacBook Pro 16-inch (M3 Pro)",
  "MacBook Pro 16-inch (M2 Max)",
  "MacBook Pro 16-inch (M2 Pro)",
  "MacBook Pro 16-inch (M1 Max)",
  "MacBook Pro 16-inch (M1 Pro)",
  "MacBook Pro 16-inch (2019)",
  "MacBook Pro 14-inch (M4 Max)",
  "MacBook Pro 14-inch (M4 Pro)",
  "MacBook Pro 14-inch (M4)",
  "MacBook Pro 14-inch (M3 Max)",
  "MacBook Pro 14-inch (M3 Pro)",
  "MacBook Pro 14-inch (M3)",
  "MacBook Pro 14-inch (M2 Max)",
  "MacBook Pro 14-inch (M2 Pro)",
  "MacBook Pro 14-inch (M1 Max)",
  "MacBook Pro 14-inch (M1 Pro)",
  "MacBook Pro 13-inch (M2)",
  "MacBook Pro 13-inch (M1)",
  "MacBook Pro 13-inch (2020 Intel)",
  "MacBook Pro 13-inch (2019)",
  "MacBook Pro 13-inch (2018)",
  "MacBook Pro 13-inch (2017)",
  "MacBook Pro 13-inch (2016)",
  "MacBook Pro 15-inch (2019)",
  "MacBook Pro 15-inch (2018)",
  "MacBook Pro 15-inch (2017)",
  "MacBook Pro 15-inch (2016)",
  
  // MacBook Air
  "MacBook Air 15-inch (M3)",
  "MacBook Air 15-inch (M2)",
  "MacBook Air 13-inch (M3)",
  "MacBook Air 13-inch (M2)",
  "MacBook Air 13-inch (M1)",
  "MacBook Air 13-inch (2020 Intel)",
  "MacBook Air 13-inch (2019)",
  "MacBook Air 13-inch (2018)",
  "MacBook Air 13-inch (2017)",
  "MacBook 12-inch (2017)",
  "MacBook 12-inch (2016)",
  "MacBook 12-inch (2015)",
  
  // ==================== SMARTWATCHES ====================
  // Apple Watch
  "Apple Watch Ultra 2",
  "Apple Watch Ultra",
  "Apple Watch Series 10",
  "Apple Watch Series 9",
  "Apple Watch Series 8",
  "Apple Watch Series 7",
  "Apple Watch Series 6",
  "Apple Watch SE (2nd Gen)",
  "Apple Watch SE (1st Gen)",
  "Apple Watch Series 5",
  "Apple Watch Series 4",
  "Apple Watch Series 3",
  "Apple Watch Series 2",
  "Apple Watch Series 1",
  "Apple Watch (1st Gen)",
  
  // Samsung Galaxy Watch
  "Samsung Galaxy Watch Ultra",
  "Samsung Galaxy Watch 7",
  "Samsung Galaxy Watch FE",
  "Samsung Galaxy Watch 6 Classic",
  "Samsung Galaxy Watch 6",
  "Samsung Galaxy Watch 5 Pro",
  "Samsung Galaxy Watch 5",
  "Samsung Galaxy Watch 4 Classic",
  "Samsung Galaxy Watch 4",
  "Samsung Galaxy Watch 3",
  "Samsung Galaxy Watch Active 2",
  "Samsung Galaxy Watch Active",
  "Samsung Galaxy Watch",
  "Samsung Galaxy Fit 3",
  "Samsung Galaxy Fit 2",
  
  // ==================== EARBUDS ====================
  // Apple AirPods
  "AirPods Pro 2 (USB-C)",
  "AirPods Pro 2 (Lightning)",
  "AirPods Pro (1st Gen)",
  "AirPods Pro",
  "AirPods 4 (ANC)",
  "AirPods 4",
  "AirPods 3rd Gen",
  "AirPods 3",
  "AirPods 2nd Gen",
  "AirPods 2",
  "AirPods 1st Gen",
  "AirPods",
  "AirPods Max",
  
  // Samsung Galaxy Buds
  "Samsung Galaxy Buds 3 Pro",
  "Samsung Galaxy Buds 3",
  "Samsung Galaxy Buds FE",
  "Samsung Galaxy Buds 2 Pro",
  "Samsung Galaxy Buds 2",
  "Samsung Galaxy Buds Pro",
  "Samsung Galaxy Buds Live",
  "Samsung Galaxy Buds+",
  "Samsung Galaxy Buds",
  
  // ==================== CONTROLLERS ====================
  "DualSense Edge",
  "DualSense Controller",
  "DualSense",
  "PS5 Controller",
  "DualShock 4",
  "PS4 Controller",
  "DualShock 3",
  "PS3 Controller",
  "DualShock 2",
  "DualShock",
  "Xbox Elite Wireless Controller Series 2",
  "Xbox Elite Controller",
  "Xbox Wireless Controller",
  "Xbox One Controller",
  "Xbox 360 Controller",
  "Nintendo Switch Pro Controller",
  "Switch Pro Controller",
  "Joy-Con (L/R)",
  "Joy-Con Left",
  "Joy-Con Right",
  "Joy-Con",
  "Wii Remote Plus",
  "Wiimote",
  "Wii Remote",
  "Wii Nunchuk",
  "Nunchuk",
  "GameCube Controller",
  "Scuf Reflex Pro",
  "Scuf Reflex",
  "Scuf Instinct Pro",
  "Scuf Controller",
  
  // ==================== VR HEADSETS ====================
  "Meta Quest 3S",
  "Meta Quest 3",
  "Quest 3",
  "Meta Quest Pro",
  "Quest Pro",
  "Meta Quest 2",
  "Quest 2",
  "Oculus Quest 2",
  "Oculus Quest",
  "Oculus Rift S",
  "Oculus Rift",
  "PlayStation VR2",
  "PSVR2",
  "PlayStation VR",
  "PSVR",
  "Apple Vision Pro",
  "Vision Pro",
  "Valve Index",
  "HTC Vive Pro 2",
  "HTC Vive Pro",
  "HTC Vive",
  "Vive Pro 2",
  "Vive Pro",
  "HP Reverb G2",
  "Pico 4",
  
  // ==================== DESKTOPS ====================
  "Mac Studio (M2 Ultra)",
  "Mac Studio (M2 Max)",
  "Mac Studio (M1 Ultra)",
  "Mac Studio (M1 Max)",
  "Mac Studio",
  "Mac Pro (M2 Ultra)",
  "Mac Pro (2019)",
  "Mac Pro",
  "Mac Mini (M4 Pro)",
  "Mac Mini (M4)",
  "Mac Mini (M2 Pro)",
  "Mac Mini (M2)",
  "Mac Mini (M1)",
  "Mac Mini (2018)",
  "Mac Mini",
  "iMac 24-inch (M4)",
  "iMac 24-inch (M3)",
  "iMac 24-inch (M1)",
  "iMac 27-inch (2020)",
  "iMac 27-inch (2019)",
  "iMac Pro",
  "iMac",
  
  // ==================== SMART HOME ====================
  "Echo Show 21",
  "Echo Show 15",
  "Echo Show 10",
  "Echo Show 8",
  "Echo Show 5",
  "Amazon Echo Show",
  "Echo Hub",
  "Amazon Echo",
  "Echo Dot with Clock",
  "Echo Dot",
  "Echo Pop",
  "Echo Studio",
  "Echo Auto",
  "Google Nest Hub Max",
  "Google Nest Hub",
  "Nest Hub",
  "Google Nest Audio",
  "Nest Audio",
  "Google Nest Mini",
  "Nest Mini",
  "Google Home",
  "Google Home Mini",
  "HomePod (2nd Gen)",
  "HomePod Mini",
  "HomePod",
  "Apple TV 4K",
  "Apple TV HD",
  "Apple TV",
  "Ring Video Doorbell",
  "Ring Doorbell",
  "Ring Floodlight Cam",
  "Ring Spotlight Cam",
  "Nest Doorbell",
  "Nest Cam",
  "Nest Thermostat",
  "Nest Learning Thermostat",
  "Roku Ultra",
  "Roku Streaming Stick",
  "Roku Express",
  "Roku",
  "Sonos Arc",
  "Sonos Beam",
  "Sonos Ray",
  "Sonos One",
  "Sonos Move",
  "Sonos Roam",
  
  // ==================== DRONES ====================
  "DJI Mavic 3 Pro",
  "DJI Mavic 3 Classic",
  "DJI Mavic 3",
  "DJI Air 3",
  "DJI Air 2S",
  "DJI Mini 4 Pro",
  "DJI Mini 4K",
  "DJI Mini 3 Pro",
  "DJI Mini 3",
  "DJI Mini 2 SE",
  "DJI Mini 2",
  "DJI FPV",
  "DJI Avata 2",
  "DJI Avata",
  "Mavic 3",
  "DJI Mini",
  "DJI Drone",
  
  // ==================== ACTION CAMERAS ====================
  "GoPro Hero 13 Black",
  "GoPro Hero 12 Black",
  "GoPro Hero 11 Black Mini",
  "GoPro Hero 11 Black",
  "GoPro Hero 10 Black",
  "GoPro Hero 9 Black",
  "GoPro Max",
  "GoPro Hero",
  "GoPro",
  "DJI Osmo Action 4",
  "DJI Osmo Action 3",
  "DJI Pocket 3",
  "DJI Pocket 2",
  "Insta360 X4",
  "Insta360 X3",
  "Insta360 ONE RS",
  "Insta360 Ace Pro",
  "Insta360",
  
  // ==================== E-READERS ====================
  "Kindle Scribe",
  "Kindle Oasis",
  "Kindle Paperwhite (2024)",
  "Kindle Paperwhite Signature Edition",
  "Kindle Paperwhite",
  "Kindle (2024)",
  "Kindle (2022)",
  "Kindle",
  "Kindle Kids",
  "Kobo Elipsa 2E",
  "Kobo Elipsa",
  "Kobo Sage",
  "Kobo Libra 2",
  "Kobo Clara 2E",
  "Kobo",
  "reMarkable 2",
  "reMarkable",
  "Nook GlowLight 4",
  "Nook",
  
  // ==================== ACCESSORIES ====================
  "Apple Pencil Pro",
  "Apple Pencil (USB-C)",
  "Apple Pencil 2nd Generation",
  "Apple Pencil 1st Generation",
  "Apple Pencil",
  "Samsung S Pen Pro",
  "Samsung S Pen",
  "S Pen",
  "Apple Magic Keyboard",
  "Magic Keyboard",
  "Apple Magic Mouse",
  "Magic Mouse",
  "Apple Magic Trackpad",
  "Magic Trackpad",
  "MagSafe Charger",
  "MagSafe Battery Pack",
  "MagSafe",
];

// Search function for autocomplete
export function searchDevices(query: string, limit: number = 10): string[] {
  if (!query || query.length < 2) return [];
  
  const normalizedQuery = query.toLowerCase().trim();
  
  // Exact prefix matches first
  const prefixMatches = devices.filter(device => 
    device.toLowerCase().startsWith(normalizedQuery)
  );
  
  // Then contains matches
  const containsMatches = devices.filter(device => 
    device.toLowerCase().includes(normalizedQuery) &&
    !device.toLowerCase().startsWith(normalizedQuery)
  );
  
  // Combine and limit
  return [...prefixMatches, ...containsMatches].slice(0, limit);
}

// Example usage:
// searchDevices("ps") → ["PS5", "PS5 Digital", "PS4", "PS4 Pro", "PS4 Slim", "PS3", ...]
// searchDevices("iphone 14") → ["iPhone 14 Pro Max", "iPhone 14 Pro", "iPhone 14 Plus", "iPhone 14"]
// searchDevices("galaxy s24") → ["Samsung Galaxy S24 Ultra", "Samsung Galaxy S24+", "Samsung Galaxy S24", ...]
